#ifndef __FSOB_FUNCTIONS_H__
#define __FSOB_FUNCTIONS_H__

#define SPECIALFUNCTIONSBASE (0)
#define FILEFUNCTIONSBASE    (4096)
#define BADGEFUNCTIONSBASE   (8192)

enum SPECIALFUNCTIONS {
    EXECFILE = 0,
    HEARTBEAT,
    PYTHONSTDIN,
    APPFSBOOT,
    SPECIALFUNCTIONSLEN
};

enum FILEFUNCTIONS {
    GETDIR=0,
    READFILE,
    WRITEFILE,
    DELFILE,
    DUPLFILE,
    MVFILE,
    MAKEDIR,
    APPFSDIR,
    APPFSDEL,
    APPFSWRITE,
    FILEFUNCTIONSLEN
};

enum BADGEFUNCTIONS {
    BADGEFUNCTIONSLEN = 0
};

#endif